// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn7JYJN_I1h7zbu-ExMjIl7zKwp7uOQs0',
    appId: '1:470283704477:web:f3d180eaa5c8b6cfe19c74',
    messagingSenderId: '470283704477',
    projectId: 'codequest-854e8',
    authDomain: 'codequest-854e8.firebaseapp.com',
    storageBucket: 'codequest-854e8.firebasestorage.app',
    measurementId: 'G-5TFY2J4QJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8VjenyxQUCxYzcm7gr8RfyuFD_MkoDVc',
    appId: '1:470283704477:android:3daf7284a4b714a4e19c74',
    messagingSenderId: '470283704477',
    projectId: 'codequest-854e8',
    storageBucket: 'codequest-854e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJdLyp0w8sKj9O_EBD8CIs01EeaFWySMA',
    appId: '1:470283704477:ios:94de0da5e34de66ee19c74',
    messagingSenderId: '470283704477',
    projectId: 'codequest-854e8',
    storageBucket: 'codequest-854e8.firebasestorage.app',
    iosBundleId: 'com.example.codequest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJdLyp0w8sKj9O_EBD8CIs01EeaFWySMA',
    appId: '1:470283704477:ios:94de0da5e34de66ee19c74',
    messagingSenderId: '470283704477',
    projectId: 'codequest-854e8',
    storageBucket: 'codequest-854e8.firebasestorage.app',
    iosBundleId: 'com.example.codequest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn7JYJN_I1h7zbu-ExMjIl7zKwp7uOQs0',
    appId: '1:470283704477:web:89736430c9b2b47de19c74',
    messagingSenderId: '470283704477',
    projectId: 'codequest-854e8',
    authDomain: 'codequest-854e8.firebaseapp.com',
    storageBucket: 'codequest-854e8.firebasestorage.app',
    measurementId: 'G-50VWTK5S5Z',
  );
}
